#######################################################################################
# Book settings
title                       : "Johanna's webpage"  # The title of the book. Will be placed in the left navbar.
author                      :  Johanna  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : []  # A path to the book logo
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
